FROM docker.io/jupyter/minimal-notebook:python-3.10

LABEL org.opencontainers.image.authors "Dušan Simić <dusan.s@maker.rs>"
LABEL org.opencontainers.image.url "https://github.com/makers-ns/gozinc2023"
LABEL org.opencontainers.image.title "GoZINC 2023 Jupyter Notebook"

# Install opencv dependencies

USER root
RUN apt-get update
RUN apt-get -y install ffmpeg libsm6 libxext6

# Install pipenv
USER ${NB_UID}
RUN pip install pipenv

# Install workshop dependencies

COPY --chown=${NB_UID}:${NB_GID} Pipfile .
COPY --chown=${NB_UID}:${NB_GID} Pipfile.lock .
RUN pipenv install --system
RUN fix-permissions "${CONDA_DIR}"
RUN fix-permissions "/home/${NB_USER}"
RUN rm -rf Pipfile Pipfile.lock

# Copy workshop notebook

COPY --chown=${NB_UID}:${NB_GID} notebook.ipynb .
RUN mkdir -p /home/${NB_USER}/images
RUN mkdir -p /home/${NB_USER}/rig
COPY --chown=${NB_UID}:${NB_GID} rig/calib.npz rig
COPY --chown=${NB_UID}:${NB_GID} images/corners_img.png images
COPY --chown=${NB_UID}:${NB_GID} images/my_photo01.jpg images
COPY --chown=${NB_UID}:${NB_GID} images/my_photo05.jpg images
COPY --chown=${NB_UID}:${NB_GID} images/walls.jpg images/maze01.jpg
